export const ADD_USERS_TO_USERS_LIST = 'ADD_USERS_TO_USERS_LIST';
export const SET_LOADING_USERS_LIST_DATA_STATUS =
  'SET_LOADING_USERS_LIST_DATA_STATUS';
export const SET_LOADING_USER_DETAILS_DATA_STATUS =
  'SET_LOADING_USERS_DETAILS_DATA_STATUS';
export const SET_LOADING_USER_REPOS_DATA_STATUS =
  'SET_LOADING_USER_REPOS_DATA_STATUS';
export const INCREMENT_START_INDEX = 'INCREMENT_START_INDEX';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_PAGE = 'SET_PAGE';
